# Generated by Django 4.2.7 on 2025-08-24 14:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('college_name', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer-not-to-say', 'Prefer not to say')], max_length=20, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('social_link1', models.URLField(blank=True, null=True)),
                ('social_link2', models.URLField(blank=True, null=True)),
                ('is_beginner', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('desired_skills', models.ManyToManyField(blank=True, related_name='desired_by_users', to='backend.skill')),
                ('known_skills', models.ManyToManyField(blank=True, related_name='known_by_users', to='backend.skill')),
                ('my_skills', models.ManyToManyField(blank=True, related_name='users', to='backend.skill')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
