# Generated by Django 4.2.7 on 2025-09-15 08:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_user_department_remove_user_social_link1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HackathonExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizer_name', models.CharField(max_length=200)),
                ('hackathon_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('achievements', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hackathon_experiences', to='backend.user')),
            ],
            options={
                'verbose_name': 'Hackathon Experience',
                'verbose_name_plural': 'Hackathon Experiences',
                'ordering': ['-created_at'],
            },
        ),
    ]
